- name: Install Nginx
  hosts: localhost
  connection: local
  become: true
  tasks:
     - name: Install Package
       yum:
          name: nginx
          state: latest
     - name: Start the service
       service:
         name: nginx
         state: started
         enabled: yes
                